### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by MinecraftPublisher** [MinecraftPublisher/PlugDOS#1]
- [ ] Do nothing
 - [ ] Do nothing again
 - [ ] Do even more nothing

**Comment by MinecraftPublisher** [comment]
- [x] Where is my table
